        # NumPy Array-creating numpy array from list

In [1]:
my_list=[1,2,3]


In [3]:
import numpy as np

In [4]:
np.array(my_list)
# cast a 1 D array

array([1, 2, 3])

In [ ]:
# Cast a 2 D array- list of lists


In [7]:
my_list_2=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_list_2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# common way to create numpy array


In [11]:
np.arange(0,10,1)
#1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# create array of all zeroes

In [13]:
np.zeros(3)
#1 D 

array([ 0.,  0.,  0.])

In [14]:
np.zeros((3,5))
#2D

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
np.ones(4)
#1D

array([ 1.,  1.,  1.,  1.])

In [16]:
np.ones((3,5))
#2D

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [ ]:
#Linspace to create numpy

In [17]:
np.linspace(0,5,10)
#1D

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [ ]:
#identity matrix for dealing linear algebra

In [19]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [ ]:
#array of random number

In [21]:
np.random.rand(5)
#1 D array of univeral distributed numbers between 0 and 1

array([ 0.48485532,  0.79444778,  0.32976823,  0.7545017 ,  0.17274081])

In [22]:
np.random.rand((2,3))

TypeError: an integer is required

In [23]:
np.random.rand(2,3)
#2D - remember we are not passing a tuple in this case

array([[ 0.94468581,  0.17659951,  0.84190749],
       [ 0.78839123,  0.2047998 ,  0.69124167]])

In [ ]:
# randn- from standard normal distribution, galcian distribution 

In [25]:
np.random.randn(5)
#1D array

array([-0.93786315,  0.97251499, -0.9765574 ,  0.94299358, -0.53788207])

In [26]:
np.random.randn(5,5)
#2D array

array([[ 0.76501997, -1.0252876 ,  1.06694181,  0.6719241 , -1.88784264],
       [ 1.38375368, -0.95437309,  0.90483861,  0.17503422, -1.72436724],
       [-0.53485859,  0.67342251, -0.72212565, -0.55087496,  0.04986235],
       [-0.25119102, -1.32694417, -1.18870779, -0.63707321,  0.48649961],
       [-0.44145893, -0.54388616, -0.9912307 ,  0.77472553,  0.91017776]])

In [ ]:
#randint  

In [28]:
np.random.randint(0,10)
# gives a random integer

1

In [29]:
np.random.randint(0,10,5)
#1D array

array([6, 2, 8, 3, 7])

In [36]:
arr=np.arange(0,25)
#arr=np.arrange(0,25,1)
#arr=np.arrange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
ranarr=np.random.randint(0,50,9)

In [48]:
ranarr

array([37, 48,  0, 21, 35, 27, 14,  9, 34])

Methods on array

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr

array([30,  3, 39,  5,  6,  9, 34, 26, 28, 27])

In [44]:
ranarr.max()

39

In [49]:
ranarr.reshape(3,3)

array([[37, 48,  0],
       [21, 35, 27],
       [14,  9, 34]])

In [50]:
ranarr.argmax()

1

In [51]:
ranarr.argmin()

2

In [53]:
arr.shape

(25,)

In [54]:
arr.dtype

dtype('int64')

In [55]:
from numpy.random import randint


In [57]:
randint(2,10,4)

array([9, 8, 9, 6])

    # numpy indexing and selection


In [60]:
arr=np.arange(11)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[7]

7

In [63]:
arr[1:3]

array([1, 2])

In [64]:
arr[:5]

array([0, 1, 2, 3, 4])

In [65]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr[0:5]=100

In [68]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [4]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [71]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [76]:
arr_2d[0][0]

5

In [79]:
arr_2d[0,0]

5

In [80]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [5]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [6]:
arr = np.arange(1,11)

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [9]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

    # Basic operations on numpy array
    NumPy operations- Array with Array, Array with Scalar, Universal Array Functions

In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr*4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [8]:
arr/0

//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':
//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf])

In [10]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [11]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [12]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [ ]:
#np.max and arr.max() are same

In [13]:
arr.max()

10

In [15]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [16]:
np.log(arr)

//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])